country_codes = [
        ('Argentina', 'AR'),
        ('Australia', 'AU'),
        ('Austria', 'AT'),
        ('Belgium', 'BE'),
        ('Brazil', 'BR'),
        ('Canada', 'CA'),
        ('Chile', 'CL'),
        ('Denmark', 'DK'),
        ('Finland', 'FI'),
        ('France', 'FR'),
        ('Germany', 'DE'),
        ('Hong Kong SAR', 'HK'),
        ('India', 'IN'),
        ('Indonesia', 'ID'),
        ('Italy', 'IT'),
        ('Japan', 'JP'),
        ('Korea', 'KR'),
        ('Malaysia', 'MY'),
        ('Mexico', 'MX'),
        ('Netherlands', 'NL'),
        ('New Zealand', 'NZ'),
        ('Norway', 'NO'),
        ("People's Republic of China", 'CN'),
        ('Poland', 'PL'),
        ('Portugal', 'PT'),
        ('Republic of the Philippines', 'PH'),
        ('Russia', 'RU'),
        ('Saudi Arabia', 'SA'),
        ('South Africa', 'ZA'),
        ('Spain', 'ES'),
        ('Sweden', 'SE'),
        ('Switzerland', 'CH'),
        ('Taiwan', 'TW'),
        ('Turkey', 'TR'),
        ('United Kingdom', 'GB'),
        ('United States', 'US')
    ]